### ISSUE TITLE
Document the required GHC version

### ISSUE THREAD

**Issue by ndmitchell** [nomeata/ghc-proofs#1]
Does this only work with GHC HEAD? The documentation says that the examples only work with GHC HEAD, but does any of it work with GHC 8.0.*?

**Comment by nomeata** [comment]
It compiles with GHC-8.0.*, but things will inline less aggressively and CSE will not be run, so less proofs will go through.

You might be interested to hear that I started to look at the HLint hints and see how many of these I can prove :-)

**Comment by ndmitchell** [comment]
That was indeed my plan: https://github.com/ndmitchell/hlint/issues/309

**Comment by hansroland** [comment]
This issue has been solved with PR [#4](https://github.com/nomeata/ghc-proofs/pull/4) and [#5](https://github.com/nomeata/ghc-proofs/pull/5). The [README](https://github.com/nomeata/ghc-proofs/blob/master/README.md) now documents the supported GHC versions, currently GHC 8.2, 8.4 and 8.6. GHC HEAD (a codebase that changes more or less every day) is no longer recommended.
